ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.sentrysmp.HttpKt.configureHttp
      - com.sentrysmp.SecurityKt.configureSecurity
      - com.sentrysmp.KoinKt.configureKoin
      - com.sentrysmp.RoutingKt.configureRouting
